const reasons = [
  "Your smile lights up every room",
  "Your laugh is my favorite sound",
  "The way you understand me without words",
  "Your kindness to everyone you meet",
  "How you make me feel safe",
  "Your beautiful eyes",
  "The way you care for others",
  "Your strength when things get hard",
  "Your sense of humor",
  "Your honesty and loyalty",
  "The way you believe in me",
  "Your gentle nature",
  "Your intelligence",
  "How you challenge me to be better",
  "Your patience with me",
  "The way you support my dreams",
  "Your creativity",
  "Your warmth",
  "The way you hold my hand",
  "Your unconditional love",
  "Your voice",
  "The way you look at me",
  "Your compassion",
  "Your sense of adventure",
  "How you make ordinary days special",
  "Your intuition",
  "The way you remember the small things",
  "Your beauty inside and out",
  "How you forgive and forget",
  "Your grace",
  "The way you make time for me",
  "Your curiosity about the world",
  "Your ambition",
  "The way you handle stress",
  "Your love for family",
  "How you make me a better person",
  "Your reliability",
  "The way you comfort me",
  "Your optimism",
  "Your attention to detail",
  "How you make me laugh when I'm sad",
  "Your bravery",
  "The way you share your thoughts",
  "Your respect for others",
  "Your love of life",
  "How you handle challenges",
  "Your calm presence",
  "The way you inspire me",
  "Your appreciation for the little things",
  "Your generosity",
  "The way you trust me",
  "Your emotional intelligence",
  "How you celebrate my wins",
  "Your flexibility",
  "The way you listen",
  "Your thoughtfulness",
  "Your ability to make me feel loved",
  "Your punctuality",
  "The way you prioritize us",
  "Your wisdom",
  "How you handle disappointment",
  "Your confidence",
  "The way you show affection",
  "Your commitment",
  "Your openness to try new things",
  "How you lift me up",
  "Your consistency",
  "The way you make plans for us",
  "Your love for music",
  "Your cooking",
  "The way you take care of yourself",
  "Your faith in us",
  "Your energy",
  "The way you make me feel home",
  "Your presence",
  "Your acceptance of me",
  "The way you say my name",
  "Your appreciation for me",
  "How you deal with uncertainty",
  "Your mindfulness",
  "The way you plan for the future",
  "Your love for travel",
  "Your creativity in the bedroom",
  "The way you handle criticism",
  "Your love for animals",
  "Your spontaneous side",
  "The way you comfort your friends",
  "Your love for learning",
  "Your humility",
  "The way you make memories with me",
  "Your touch",
  "Your gratitude for everything",
  "How you face your fears",
  "Your consistency in love",
  "The way you say I love you",
  "Your beautiful heart",
  "How you make every moment count",
  "Your endless love",
  "You are my everything"
]

export default reasons